In [2]:
import numpy as np

In [4]:
#scaler array :- if itr contains only one elemnt
ar=np.array(7)
np.ndim(ar)

0

In [6]:
#reshaping the array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
newarr=arr.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Numpy major and minors


In [7]:
#axis =1 (column)
#axis = 0 (row)
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#by default it is in row
# with out specification of the column it will trun the array into 1d aray
np.append(a,[[7,8,9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#append in row
np.append(a,[[11,22,33]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33]])

In [13]:
#appendt the new column appending in column
np.append(a,[[66],[77]],axis=1)

array([[ 1,  2,  3, 66],
       [ 4,  5,  6, 77]])

Insert into the numpy array

In [15]:
b=np.array([[1,2],
           [3,4],
           [5,6]])

b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
#syntax= np.insert(arr,index,newelement)
#if we add iD arrray
np.insert(b,2,[44,33])

array([ 1,  2, 44, 33,  3,  4,  5,  6])

In [23]:
#row insert
np.insert(b,1,[20,30],axis=0)

array([[ 1,  2],
       [20, 30],
       [ 3,  4],
       [ 5,  6]])

In [28]:
#column insert #no of row == values to insert in arr
np.insert(b,2,[11,33,77],axis=1)

array([[ 1,  2, 11],
       [ 3,  4, 33],
       [ 5,  6, 77]])

Delete In np array

In [30]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.ndim(a)

2

In [33]:
#delete according to the arra indexd in array 
#it's convert intp the 1D array and delete the partricular index
np.delete(c,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [34]:
#if we givw the axis it will delete the entire rwo or column based on the axis valiues
np.delete(c,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [35]:
#in terms of row
np.delete(c,0,axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

Hstack and Vstack

### Hsatack is used to join the array horizontally (by row)
### Vstack is used to join the array verticaly(by Column)

In [1]:
d=np.array([1,2,3])
e=np.array([4,5,6])

NameError: name 'np' is not defined

In [40]:
# hastack 
result=np.hstack((d,e))
result

array([1, 2, 3, 4, 5, 6])

In [43]:
#vstack
r2=np.vstack((d,e))
r2
np.ndim(r2)

2

## numpy concatination

We can conacte the tw0 array by row and column using axis

we can add onlly same dimensional array

## numpy array slicing 

arr[row,col]

In [46]:
a1=np.array([1,2,3,4,5,6,7])
a1

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
a1[1:5] #ending wil be excluded
a1[4:]  #onwrads the 4th position start to all 
a1[:4]  #first 4 element

array([1, 2, 3, 4])

In [51]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,19]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 19]])

In [55]:
#2d array slicing 
a2[1,1:4]

array([7, 8, 9])

In [58]:
a2[:,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [59]:
a2[1,2:4]

array([8, 9])

### 3d array

In [68]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
np.ndim(a3)

3

#### syntax[matrix,row, colomn]

In [71]:
a3[:2,1:,:2]

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]]])

### View and copy

In [74]:
# copy method 
#does not effect in original array
c1=np.array([1,2,3,4,5])
c1
copy=c1.copy()

In [77]:
copy[0]=100
print(c1)
print(copy)

[1 2 3 4 5]
[100   2   3   4   5]


In [80]:
#view
v= c1.view()
v[0]=178
print*